# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_build:
      - mv $READTHEDOCS_OUTPUT/html/doxygen/* $READTHEDOCS_OUTPUT/html/

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/sphinx/conf.py
