/******************************************************************************
 *
 * This file is part of the CAROM distribution.  For full copyright
 * information, see COPYRIGHT.
 *
 * Copyright:   (c) 2013-2014 Lawrence Livermore National Security, LLC
 * Description: A class that writes basis vectors to a file.
 *
 *****************************************************************************/

#ifndef included_BasisWriter_h
#define included_BasisWriter_h

#include "Database.h"
#include <string>

namespace CAROM {

class SVDBasisGenerator;

/**
 * Class BasisWriter writes the basis vectors created by an SVDBasisGenerator.
 */
class BasisWriter {
   public:
      /**
       * @brief Constructor.
       *
       * @pre basis_generator != 0
       * @pre !base_file_name.empty()
       *
       * @param[in] basis_generator The generator of the basis vectors to be
       *                            written.
       * @param[in] base_file_name The base part of the name of the files
       *                           holding the basis vectors.
       * @param[in] db_format Format of the file to read.
       *                      One of the implemented file formats defined in
       *                      Database.
       */
      BasisWriter(
         SVDBasisGenerator* basis_generator,
         const std::string& base_file_name,
         Database::formats db_format = Database::HDF5);

      /**
       * @brief Destructor.
       */
      ~BasisWriter();

      /**
       * @brief Write basis vectors generated by d_basis_generator.
       */
      void
      writeBasis();

   private:
      /**
       * @brief Unimplemented default constructor.
       */
      BasisWriter();

      /**
       * @brief Unimplemented copy constructor.
       */
      BasisWriter(
         const BasisWriter& other);

      /**
       * @brief Unimplemented assignment operator.
       */
      BasisWriter&
      operator = (
         const BasisWriter& rhs);

      /**
       * @brief Basis generator whose basis vectors are being written.
       */
      SVDBasisGenerator* d_basis_generator;

      /**
       * @brief Database to which basis vectors are being written.
       */
      Database* d_database;

      /**
       * @brief Number of time intervals for which basis vectors have been
       * written.
       */
      int d_num_intervals_written;
};

}

#endif
