#!/bin/sh

###############################################################################
#
#  Copyright (c) 2013-2019, Lawrence Livermore National Security, LLC
#  and other libROM project developers. See the top-level COPYRIGHT
#  file for details.
#
#  SPDX-License-Identifier: (Apache-2.0 OR MIT)
#
###############################################################################

##
## Generate dependency information for all files in the current directory
## and subdirectories.
##

BIN=`dirname $0`
bindir=`cd $BIN && pwd`

PERL=${PERL:-perl}
COMP="$PERL $BIN/cmp.pl"

DIRS=`find . -type d -print | grep -v '\(OLD\|NEW\|BAK\|SAVE\|to_be_implemented\|noprefix\|BASELINES\|config\|scripts\|CVS\|\.svn\|\.git\|\.hg\)'`
for DIR in $DIRS ; do

   #
   # Generate a dependency file in the subdirectory if *.C files exist
   #

   echo "Checking dependencies in directory "$DIR
   FILES=`(cd $DIR; echo *.[fCc])`
   if [ "*.[fCc]" != "$FILES" ] ; then
      (cd $DIR && perl $bindir/depend.pl . '-' $FILES)

      #
      # If Makefile.depend does not exist, then create it
      #

      if [ ! -r $DIR/Makefile.depend ] ; then
         echo "   creating "$DIR/Makefile.depend
         mv -f $DIR/Makefile.depend.tmp $DIR/Makefile.depend

      #
      # Otherwise, copy if the two files are not the same.  Remove the CVS
      # portions of the header to ignore changes in date/revision/modified.
      #

      else
         if $COMP $DIR/Makefile.depend.tmp $DIR/Makefile.depend ; then
            rm -f $DIR/Makefile.depend.tmp
         else
            echo "   updating "$DIR/Makefile.depend
            mv -f $DIR/Makefile.depend.tmp $DIR/Makefile.depend
         fi
      fi
   fi
done

exit 0
