runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install libROM dependencies
    - run: DEPS_DIR="${GITHUB_WORKSPACE}/deps"
    - run: mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - run: git clone https://github.com/google/googletest
    - run: cd googletest && mkdir build && cd build
    - run: cmake .. && make && sudo make install
    - run: PATH=${DEPS_DIR}/googletest:${DEPS_DIR}/googletest/build:$PATH
    - name: Build libROM
    - run: cd ${TRAVIS_BUILD_DIR}/build
    - run: cmake -DCMAKE_BUILD_TYPE=Debug ..
    - run: make
    - run: cmake -DCMAKE_BUILD_TYPE=Optimized ..
    - run: make
    - name: Run tests
    - run: ./test_SVD
    - run: ./test_Vector
    - run: ./test_Matrix
    - run: ./test_DEIM
    - run: ./test_GNAT
    - run: ./test_QDEIM
    - run: ./test_IncrementalSVD
    - run: ./test_RandomizedSVD
    - run: mpirun -n 3 --oversubscribe test_RandomizedSVD
